###################################
# build and publish docker images #
###################################
# branch: master
# event: tag

clone:
  git:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-git

pipeline:

  # build and publish docker image for amd64 - x86
  build-amd64:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      repo: olofvndrhr/flox-dockerized
      platforms: linux/amd64
      dockerfile: Dockerfile.amd64
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: cr-dhub-username
      password:
        from_secret: cr-dhub-key

  # build and publish docker image for arm64
  build-arm64:
    when:
      #branch: master
      event: tag
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      repo: olofvndrhr/flox-dockerized
      platforms: linux/arm64
      dockerfile: Dockerfile.arm64
      auto_tag: true
      auto_tag_suffix: linux-arm64
      username:
        from_secret: cr-dhub-username
      password:
        from_secret: cr-dhub-key

  # publish docker manifest for automatic multi arch pulls
  publish-manifest:
    when:
      #branch: master
      event: tag
    image: plugins/manifest
    pull: true
    settings:
      spec: manifest.tmpl
      auto_tag: true
      ignore_missing: true
      username:
        from_secret: cr-dhub-username
      password:
        from_secret: cr-dhub-key

